mysite/myblog/urls.py
from django.conf.urls import url
from myblog import views
import validation.views
import userinfo.views

# myblog
urlpatterns = [
               url('^$', views.index, name='index'),
]

# validation
urlpatterns += [
                url('^userauth/login/$', validation.views.login, name='login'),
                url('^userauth/register/$', validation.views.register, name='register'),
                url('^userauth/logoff$', validation.views.logoff, name='logoff'),
]

# userinfomations
urlpatterns += [
               url('^userinfo/$', userinfo.views.userinfo, name='userinfo'),
               url('^userinfo/add/$', userinfo.views.publish, name='publish'),
               url('^userinfo/update/$', userinfo.views.update, name='update'),
               url('^userinfo/delete/$', userinfo.views.delete, name='delete'),
]

mysite/mysite/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from myblog import urls

urlpatterns = [
    url(r'^myblog/', include(urls, namespace='myblog')),
    url(r'^admin/', include(admin.site.urls)),
]

mysite/myblog/models.py
#from django.db import models

# Create your models here.

mysite/userinfo/models.py
from django.db import models
from validation.models import UserAuth

# Create your models here.
class Tag(models.Model):
    name = models.CharField('TagName', max_length=50, null=True)
    
    def __str__(self):
        return self.name
    
class Blog(models.Model):
    blog_title = models.CharField('BlogTitle', max_length=80)
    blog_body = models.TextField('BlogBody', max_length=5000)
    blog_tags = models.ManyToManyField(Tag)
    blog_read_count = models.IntegerField('BlogReadCount', default=0, null=True)
    blog_votes = models.IntegerField('BlogVotes', default=0, null=True)
    blog_publish_date = models.DateTimeField('BlogPublishDate', auto_now_add=True)
    blog_modify_date = models.DateTimeField('BlogPublishDate', auto_now=True)
    
    def __str__(self):
        return self.blog_title
    
class Name(models.Model):
    lastname = models.CharField('LastName', max_length=50, null=True)
    firstname = models.CharField('FirstName', max_length=50, null=True)
    promisewords = models.CharField('FirstName', max_length=50, null=True)
    
    def __str__(self):
        return self.lastname
    
class Info(models.Model):
    user = models.ForeignKey(UserAuth, null=True)
    name = models.ForeignKey(Name, null=True)
    blogs = models.ManyToManyField(Blog)
    
class Test(models.Model):
    kindof=models.CharField('KindOf', max_length=50)
    tags = models.ManyToManyField(Tag)

mysite/myblog/views.py
from django.shortcuts import render, redirect
from userinfo.models import Info

# Create your views here.

def index(request):
    user = request.session.get('userid', 'null')
    info = Info.objects.all()
    # all_user = UserAuth.objects.all()
    #context = {'blogs':blogs}
    if user != 'null':
        # user = UserAuth.objects.get(userid = user)
        #userinfo = UserInfo.objects.get(user__userid = user)
        #context ['user']= userinfo
        pass
    return render(request, 'myblog/index.html') 
    
    
    

mysite/userinfo/views.py
from django.shortcuts import render, redirect
from myblog.toolbox import shortcut_ajax, isalive
# from validation.models import UserAuth
from userinfo.models import Info, Blog, Tag
import traceback

# Create your views here.
def userinfo(request):
    if not isalive(request):return redirect('/myblog/userauth/login')
    info = Info.objects.get(user__userid=request.session.get('userid'))
    blogs = info.blogs.all().order_by('-blog_publish_date')
    context = {'user': info.name, 'blogs':blogs, 'words':info.name.promisewords}
    return render(request, 'myblog/userinfo.html', context)
    
# User publish interface
def publish(request):
    if not isalive(request):return redirect('/myblog/userauth/login')
    if request.is_ajax():
        post = request.POST
        if len(post['title']) >= 1 and len(post['content']) >= 15:
            blog = Blog.objects.create(blog_title=post.get('title'), blog_body = post.get('content'))
            info = Info.objects.get(user__userid = request.session['userid'])
            info.blogs.add(blog)
            if post.get('tags', '') != '':
                for tag in post.get('tags').split(','):
                    t = Tag.objects.create(name=tag)
                    blog.blog_tags.add(t)
                    
            return shortcut_ajax({'addCode': 0})
        else:
            return shortcut_ajax({'addCode': 1})
    else:
        return render(request, 'userinfo/userinfo_add.html')
    
def update(request):
    if not isalive(request):return redirect('/myblog/userauth/login')
    if request.is_ajax():
        post = request.POST
        if len(post['title']) >= 1 and len(post['content']) >= 15:
            info = Info.objects.get(user__userid = request.session['userid'])
            blog = info.blogs.get(id=post['blogid'])
            blog.blog_title = post['title']
            blog.blog_body = post['content']
            blog.save()
            info.blogs.get(pk=17).blog_tags.all().delete()
            if post.get('tags', '') != '':
                for tag in post.get('tags').split(','):
                    t = Tag.objects.create(name=tag)
                    blog.blog_tags.add(t)
                    
            return shortcut_ajax({'updateCode': 0})
        else:
            return shortcut_ajax({'updateCode': 1})
    else:
        return render(request, 'userinfo/userinfo_edit.html')

# User delete interface
def delete(request):
    if not isalive(request):return redirect('/myblog/userauth/login')
    if request.is_ajax():
        try:
            blogid = request.POST['blogid']
            info = Info.objects.get(user__userid=request.session.get('userid'))
            if info.blogs.get(id=blogid).delete():
                return shortcut_ajax({'delCode':0})
            else:
                raise KeyError
        except:
            print(traceback.format_exc())
            return shortcut_ajax({'delCode':1})
    else:
        return render(request, 'userinfo/userinfo_add.html')

mysite/templates/myblog/base.html
{% load i18n %}
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <title>Myblog</title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">

    <!-- Loading Bootstrap -->
    {% include 'myblog/staticfiles/head_css.html' %}

    <!-- HTML5 shim, for IE6-8 support of HTML5 elements. All other JS at the end of file. -->
    <!--[if lt IE 9]>
      <script src="js/vendor/html5shiv.js"></script>
      <script src="js/vendor/respond.min.js"></script>
    <![endif]-->
  </head>
  <body>
    <!-- load modal -->
    {% include 'myblog/modals.html' %}

    <!-- load navbar -->
    {% include 'myblog/navbar.html' %}

    <div class="container">
      {% block body %}{% endblock %}
    </div>
    <!-- /.container -->

    <!-- load script lib -->
    {% include 'myblog/staticfiles/foot_script.html' %}
    <!-- load footer -->
    {% include 'myblog/footer.html' %}
  </body>
</html>

mysite/templates/myblog/footer.html
<footer>
  <div class="container-fluid">
    <div class="row">
      <div class="col-xs-4">
        <p class="footer-title">Thank you</p>
        <dl>
          <dt>Support</dt>
          <dd>HTML5 / CSS3 / Bootstrap</dd>
          <dt>Power by</dt>
          <dd>Flat UI for free</dd>
        </dl>
      </div>
      <div class="col-xs-4">
        <p class="footer-title">Thank you</p>
        <dl>
          <dt>Support</dt>
          <dd>HTML5 / CSS3 / Bootstrap</dd>
          <dt>Power by</dt>
          <dd>Flat UI for free</dd>
        </dl>
      </div>
      <div class="col-xs-4">
        <p class="footer-title">Thank you</p>
        <dl>
          <dt>Support</dt>
          <dd>HTML5 / CSS3 / Bootstrap</dd>
          <dt>Power by</dt>
          <dd>Flat UI for free</dd>
        </dl>
      </div>
    </div>
  </div>
</footer>

mysite/templates/myblog/index.html
{% extends 'myblog/base.html' %}

{% block body %}
<div class="row">
  <div class="col-xs-9">
    {% if blogs %}
      {% for e in blogs %}
      <blockquote>
        <p class="title-box">{{e.blog_title}}</p>
        <p>{{e.blog_body}}</p>
        <small class="info-box">
          <span class="fui-time"></span> {{e.blog_publish_date}}
          <span class="fui-location"></span> City Shanghai .
          <span class="fui-user"></span> {{e.user.username}}
        </small>
      </blockquote>
      {% endfor %}
      <hr>
      <div class="text-center">
        <ul class="pagination-plain">
          <li><a href="#fakelink"><span class="fui-arrow-left"></span></a></li>
          <li><a href="#fakelink">1</a></li>
          <li><a href="#fakelink">5</a></li>
          <li><a href="#fakelink">6</a></li>
          <li><a href="#fakelink"><span class="fui-arrow-right"></a></li>
        </ul>
      </div>
    {% else %}
      <blockquote>
        <p class="title-box">System date not found.</p>
      </blockquote>
    {% endif %}
  </div>
  <div class="col-xs-3">
    
  </div>
</div>
{% endblock %}

mysite/templates/myblog/modals.html
<!-- Small modal -->
<div class="modal fade bs-example-modal-sm" id="confirm" tabindex="-1" role="dialog" aria-labelledby="mySmallModalLabel">
  <div class="modal-dialog modal-sm">
    <div class="modal-content">
      <div class="well well-sm"><span class="fui-alert-circle"></span> 你确定要这么做么？</div>    
	  <small class="text-danger"> 确认删除后将无法恢复或找回，请慎重考虑。</small>
	  <div class="modal-footer">
        <button type="button" class="btn btn-primary btn-xs" data-dismiss="modal">取消</button>
        <button type="button" class="btn btn-danger btn-xs" id="yes">确定继续</button>
      </div>
    </div>
  </div>
</div>

mysite/templates/myblog/navbar.html
<nav class="navbar navbar-inverse navbar-fixed-top" role="navigation">
  <!-- Brand and toggle get grouped for better mobile display -->
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#navbar-collapse-5">
        <span class="sr-only">Toggle navigation</span>
      </button>
      <a class="navbar-brand" href="{% url 'myblog:index' %}">iBoke</a>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="navbar-collapse-5">
      <ul class="nav navbar-nav">
        <li class="active"><a href="#">最新</a></li>
        <li><a href="#">小故事</a></li>
        <li><a href="#">问题反馈</a></li>
       </ul>
      <form class="navbar-form navbar-left" action="#" role="search">
        <div class="form-group">
          <div class="input-group">
            <input class="form-control" id="navbarInput-01" type="search" placeholder="Search">
            <span class="input-group-btn">
              <button type="submit" class="btn"><span class="fui-search"></span></button>
            </span>
          </div>
        </div>
      </form>
      <ul class="nav navbar-nav navbar-right">
        {% if user.lastname %}
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown">Welcome, {{user.lastname}} <b class="caret"></b></a>
          <ul class="dropdown-menu">
            <li><a href="{% url 'myblog:logoff' %}"><span class="fui-power"></span> logoff</a></li>
            <li><a href="{% url 'myblog:userinfo' %}"><span class="fui-document"></span> myprofile</a></li>
          </ul>
        </li>
        <li></li>
        {% else %}
        <li><a href="{% url 'myblog:login' %}"></span>Login</a></li>
        {% endif %}
      </ul>
    </div><!-- /.navbar-collapse -->
  </div>
</nav>

<!-- message -->
<div id="msgbox"></div>

mysite/templates/myblog/userauth-register.html
{% extends 'myblog/base.html' %}

{% block body %}
<div class="col-xs-0 col-sm-2 col-md-3">
</div>
<div class="col-xs-12 col-sm-8 col-md-6">
  <div class="panel panel-default" id="registerbox">
    <div class="panel-heading"><span class="fui-bookmark"></span> Welcom to register Myblog App.</div>
    <div class="panel-body">
      <form id="register-form" method="post" action="{% url 'myblog:register' %}">
      {% csrf_token %}
        <div class="login-form">
        <div class="form-group">
            <input type="text" class="form-control login-field" value="" placeholder="Enter your first name" id="first-name" />
            <label class="login-field-icon fui-new" for="first-name"></label>
          </div>

          <div class="form-group">
            <input type="text" class="form-control login-field" value="" placeholder="Enter your last name" id="last-name" />
            <label class="login-field-icon fui-new" for="last-name"></label>
          </div>

          <div class="form-group">
            <input type="text" class="form-control login-field" value="" placeholder="Enter your E-mail" id="login-mail" />
            <label class="login-field-icon fui-mail" for="login-mail"></label>
          </div>

          <div class="form-group">
            <input type="password" class="form-control login-field" value="" placeholder="Password" id="login-pass" />
            <label class="login-field-icon fui-lock" for="login-pass"></label>
          </div>

          <div class="form-group">
            <input type="password" class="form-control login-field" value="" placeholder="Password confirm" id="pass-confirm" />
            <label class="login-field-icon fui-lock" for="pass-confirm"></label>
          </div>

          <label class="checkbox" for="checkbox2">
            <input type="checkbox" checked="checked" value="" id="checkbox2" data-toggle="checkbox" checked="">
            <a href="#">&lt;&lt;Private Policy&gt;&gt;</a>&nbsp;&nbsp;Igree the private policy. 
          </label>
          <button type="button" class="btn btn-success btn-lg btn-block" id="register">Sign up</button>
          <a class="login-link" id="goLogin" href="{% url 'myblog:login' %}">Already have an account ?</a>
        </div>
      </form>
    </div>
  </div>
</div>
<div class="col-xs-0 col-sm-8 col-md-3">
</div>
{% endblock %}

mysite/templates/myblog/userauth.html
{% extends 'myblog/base.html' %}

{% block body %}
<div class="col-xs-0 col-sm-2 col-md-3">
</div>
<div class="col-xs-12 col-sm-8 col-md-6">
  <!-- login -->
  <div class="panel panel-default" id="loginbox">
    <div class="panel-heading">
      <span class="icon-lightbulb"></span> Welcom to login Myblog App.
    </div>
    <div class="panel-body">
      <form id="userauth-form" method="post" action="{% url 'myblog:login' %}">
      {% csrf_token %}
        <div class="login-form">
          <div class="form-group">
            <input type="text" class="form-control login-field" value="" placeholder="Enter your E-mail" id="login-mail" />
            <label class="login-field-icon fui-mail" for="login-mail"></label>
          </div>

          <div class="form-group">
            <input type="password" class="form-control login-field" value="" placeholder="Password" id="login-pass" />
            <label class="login-field-icon fui-lock" for="login-pass"></label>
          </div>
          
          <input type="checkbox" checked="checked" value="" id="remember" data-toggle="checkbox" checked="">
          Remember ?
          <br>
	        <button type="button" class="btn btn-inverse btn-lg btn-block" id="login">Sign in</button>
          <a class="login-link" id="goRegister" href="{% url 'myblog:register' %}">Create yourself account now ?</a>
        </div>
      </form>
    </div>
  </div>
</div>
<div class="col-xs-0 col-sm-2 col-md-3">
</div>
{% endblock %}

mysite/templates/myblog/userinfo.html
{% extends 'myblog/base.html' %}
{% load staticfiles %}

{% block body %}
<div class="row">
  <div class="col-xs-12 col-sm-3 col-md-3" id="mymenu">
    <div class="panel panel-default">
      <div class="panel-body">
        <div class="sidebar-menu text-center">
          <img src="{% static 'myblog/img/default-head.png' %}" class="img-circle">
          {% if words %}
          <hr>
          <small>{{words|title|truncatechars:30}}</small>
          {% endif %}
          <hr>
          <a href="#userMeun" class="nav-header menu-first collapsed text-center" data-toggle="collapse"><span class="fui-home"></span> Blog Manage</a>
          <ul id="userMeun" class="nav nav-list collapse menu-second">
            <li> <a id="alldoc" href="{% url 'myblog:userinfo' %}">All</a></li>
            <li><span class="fui-new"></span> <a id="newdoc" href="{% url 'myblog:publish' %}">New</a></li>
          </ul>
        </div>
      </div>
    </div>
  </div>
  <div class="col-xs-12 col-sm-9 col-md-9">
    {% block userinfo_content %}
      {% if blogs %}
        {% for e in blogs %}
        <div class="panel panel-default" id="content-box">
          <div class="panel-body">
            <div class="row">
              <div class="col-xs-10 col-sm-8 col-md-10">
                <strong class="title-box">{{forloop.counter}}. {{e.blog_title}}</strong>
              </div>
              <div class="col-xs-2 col-sm-4 col-md-2">
                <form action="{% url 'myblog:delete' %}" method="post" class="form-group" id="modify-form" bokeid="{{e.id}}">
                  {% csrf_token %}
                    <div class="btn-group" role="group">
                      <button title="edit" data-placement="top" data-toggle="tooltip" class="btn btn-success btn-xs" id="edit" type="button"><span class="fui-new"></span></button>
                      <button title="delete" data-placement="top" data-toggle="tooltip" class="btn btn-danger btn-xs" id="delete" type="button"><span class="fui-trash"></span></button>
                    </div>
                </form>
              </div>
            </div>
            <div class="row">
              <div class="col-xs-12 col-sm-12 col-md-12">
                <p>{{e.blog_body|linebreaks}}</p>
              </div>
            </div>
          </div>
        </div>
        {% endfor %}
        <hr class="hrstyle-default">
        <div class="text-center">
          <ul class="pagination-plain">
            <li><a href="#fakelink"><span class="fui-arrow-left"></span></a></li>
            <li><a href="#fakelink">1</a></li>
            <li><a href="#fakelink"><span class="fui-arrow-right"></a></li>
          </ul>
        </div>
      {% else %}
      <blockquote>
        <p class="title-box">You don't have anyone blog.</p>
      </blockquote>
      {% endif %}      
    {% endblock %}
  </div>
</div>
{% endblock %}